networks:
    completion:
        recipe: networks/completion|ddad
        checkpoint: /media/hao/CODE/MODEL/DEPTH/R3D3/completion_ddad.ckpt
        pretrained_encoder: False
evaluation:
    depth:
        recipe: evaluation/depth|ddad
    trajectory:
        root: training_arch
        file: TrajectoryMetric
datasets:
    validation:
        root: [ datasets ]
        name: [ DDAD ]
        path: [ /media/hao/CV/DEPTH/DDAD/ddad_train_val/ ]
        split: [ val ]
        augmentation:
            resize: [ 384, 640 ]
        squeeze_sensor: [ False ]
        labels: [ pose, depth ]
        cameras: [ [ 'camera_01', 'camera_05', 'camera_06', 'camera_07', 'camera_08', 'camera_09' ] ]
